name: bear
author: Ogromny <ogromnycoding@gmail.com>
version: 0.4.1
description: A simple web framework in Dart
environment:
  sdk: ">=2.0.0"
dev_dependencies:
  test: any
  http: any
dependencies:
  path: any
  mime: any